spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.172.202:3306/springcloudstudy?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSl=true&useUnicode=true
    username: root
    password: 123456
  application:
    name: bookservice
  cloud:
    nacos:
      discovery:
        # 配置Nacos注册中心地址
        server-addr: http://43.138.172.202:8848/
#        ephemeral: false
server:
  port: 8011
